run:
  timeout: "5m"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
  go: "1.23"
linters-settings:
  gocyclo:
    min-complexity: 20
  nakedret:
    max-func-lines: 1
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"]

linters:
  enable:
    - lll
    - funlen
    - gocritic
    - gocyclo
    - goimports
    - mnd
    - gosec
    - revive
    - nakedret
    - nolintlint
    - unconvert
    - wsl
    - gofumpt
    - unparam