codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: diff,flags,tree,betaprofiling
  show_carryforward_flags: false
  show_critical_paths: true
coverage:
  precision: 2
  range: 80..100
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 80
        threshold: 0
        base: auto
        only_pulls: false
        if_ci_failed: error
    project:
      default:
        target: 80
        threshold: 0
        base: auto
        only_pulls: false
        if_ci_failed: error
github_checks:
  annotations: true
ignore:
  - "**/*controller.go"
  - "**/*_dto.go"
  - "src/mocks"
  - "src/deployment"
  - "src/repository"
  - "src/infrastructure"
  - "src/domain/entity"
  - "src/common/config"
  - "src/application/service.go"
  - "src/tools"
  - "src/domain/service/registry.go"
